version: '2.23.3'
services:
  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    working_dir: /app
    command: npm run start:dev
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - database


  # PostgreSQL service
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5431:5432"
    networks:
      - database

  #pgweb service 
  pgweb:
    image: sosedoff/pgweb
    container_name: pgweb
    # restart: always
    ports: 
      - "8081:8081" 
    links: 
      - postgres:postgres
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - database

  # Frontend service
  # Vite service for development
  vite:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    image: node:20.2.0
    container_name: react-app
    working_dir: /app
    command:  npm run dev
    volumes:
      - ./frontend:/app
    ports:
      - "8000:8000"
    depends_on:
      - backend
  
  #rabbitmq
  # rabbitmq:
  #   image: "rabbitmq:latest"
  #   container_name: rabbitmq
  #   volumes:
  #     - "/var/lib/rabbitmq"
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   env_file:
  #     - .env


networks:
  database:
    driver: bridge