version: '2.23.3'
services:
  # Backend service
  backend:
    image: node:20.2.0
    container_name: backend
    working_dir: /app
    command: npm run start:prod
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - database

  # PostgreSQL service
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    networks:
      - database

  #pgweb service 
  pgweb:
    image: sosedoff/pgweb
    container_name: pgweb
    # restart: always
    ports: 
      - "8081:8081" 
    links: 
      - postgres:postgres
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - database

  # Frontend service
  # Vite service for development
  vite:
    image: node:20.2.0
    container_name: vite
    working_dir: /app
    command:  npm run dev
    volumes:
      - ./frontend:/app
    ports:
      - "8000:8000"
    depends_on:
      - backend


networks:
  database:
    driver: bridge